project:
  type: default
  output-dir: _output
  resources:
    - reference/DrPKeerthika-WINSEM2025-26_VL_BCSE205L_00100_TH_2026-03-10_Module4.pdf
    - reference/DrPKeerthika-WINSEM2025-26_VL_BCSE205L_00100_TH_2026-03-10_Module-5.pdf
  render:
    - index.qmd
    - lectures/*.qmd
    - labs/*.qmd
    - assignments/*.qmd

format:
  revealjs:
    theme: [default, theme.scss]
    width: 1280
    height: 720
    transition: fade
    slide-number: true
    hash-type: number
    center: false
    footer: "BCSE205L — Computer Architecture and Organization | VIT"
    highlight-style: github-dark
    code-overflow: wrap
    code-line-numbers: false

execute:
  echo: true
  warning: false
